import json
import os
import ast
import re
from datetime import datetime
from pathlib import Path

def enhanced_ai_detection():
    """Enhanced AI detection using multiple heuristics"""
    ai_indicators = []

    # Check for AI-generated code patterns
    ai_patterns = [
        r'# Generated by.*AI',
        r'// Generated by.*AI',
        r'@generated.*AI',
        r'AI-generated',
        r'claude|chatgpt|copilot',  # Common AI tools
        r'auto-generated|automatically generated'
    ]

    # Scan source files
    for file_path in Path('src').rglob('*.ts'):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Check for AI patterns
            for pattern in ai_patterns:
                if re.search(pattern, content, re.IGNORECASE):
                    ai_indicators.append({
                        'file': str(file_path),
                        'type': 'pattern_match',
                        'pattern': pattern,
                        'confidence': 0.8
                    })

            # Check for unusually long functions (potential AI generation)
            try:
                tree = ast.parse(content)
                for node in ast.walk(tree):
                    if isinstance(node, ast.FunctionDef):
                        if len(node.body) > 50:  # Very long functions
                            ai_indicators.append({
                                'file': str(file_path),
                                'type': 'long_function',
                                'function': node.name,
                                'confidence': 0.6
                            })
            except:
                pass  # Skip files that can't be parsed

        except Exception as e:
            print(f"Warning: Could not scan {file_path}: {e}")

    return ai_indicators

def process():
    input_path = "base-sbom.json"
    output_path = "aibom-final.json"

    if not os.path.exists(input_path):
        print(f"错误: 找不到 {input_path}")
        return

    with open(input_path, 'r') as f:
        bom = json.load(f)

    # 1. 注入全局 AI 平台元数据
    current_time = datetime.now().isoformat()
    git_commit = os.popen('git rev-parse HEAD 2>/dev/null').read().strip()
    git_branch = os.popen('git branch --show-current 2>/dev/null').read().strip()

    bom['metadata']['properties'] = [
        {"name": "ai:platform", "value": "Local-AI-Native-Flow"},
        {"name": "ai:local_build_time", "value": current_time},
        {"name": "ai:git_commit", "value": git_commit or "unknown"},
        {"name": "ai:git_branch", "value": git_branch or "unknown"},
        {"name": "ai:detection_version", "value": "2.0"}
    ]

    # 2. 增强的AI检测
    ai_indicators = enhanced_ai_detection()
    ai_files_count = len(set(indicator['file'] for indicator in ai_indicators))

    # Add AI detection summary
    bom['metadata']['properties'].extend([
        {"name": "ai:detected_files", "value": str(ai_files_count)},
        {"name": "ai:detection_indicators", "value": str(len(ai_indicators))}
    ])

    # 3. 标记AI生成的文件组件
    ai_component_count = 0
    for comp in bom.get('components', []):
        comp_name = comp.get('name', '').lower()

        # Original simple detection
        if 'ai-gen' in comp_name:
            comp.setdefault('properties', []).append({"name": "ai:generated", "value": "true"})
            comp.setdefault('properties', []).append({"name": "ai:detection_method", "value": "filename"})
            ai_component_count += 1

        # Enhanced detection based on file analysis
        for indicator in ai_indicators:
            if indicator['file'] in comp_name:
                comp.setdefault('properties', []).append({"name": "ai:generated", "value": "true"})
                comp.setdefault('properties', []).append({"name": "ai:detection_method", "value": indicator['type']})
                comp.setdefault('properties', []).append({"name": "ai:confidence", "value": str(indicator['confidence'])})
                ai_component_count += 1
                break

    # 4. 添加统计信息
    bom['metadata']['properties'].append({"name": "ai:marked_components", "value": str(ai_component_count)})

    # 5. 添加详细的AI检测报告
    if ai_indicators:
        ai_report = {
            "detection_time": current_time,
            "total_indicators": len(ai_indicators),
            "unique_files": ai_files_count,
            "indicators": ai_indicators
        }
        bom['metadata']['properties'].append({
            "name": "ai:detection_report",
            "value": json.dumps(ai_report, indent=2)
        })

    with open(output_path, 'w') as f:
        json.dump(bom, f, indent=2)

    print(f"✅ AIBOM 已生成: {output_path}")
    print(f"🤖 AI检测结果: {ai_files_count} 个文件, {len(ai_indicators)} 个指标")
    print(f"📊 标记组件: {ai_component_count} 个")

if __name__ == "__main__":
    process()