#!/bin/bash

# AI数字溯源系统实时验证脚本
# 验证GitHub Actions工作流是否正常运行

echo "🔍 AI数字溯源系统实时验证"
echo "================================="
echo ""

# 检查本地Git状态
echo "📊 本地Git状态检查:"
echo "• 当前分支: $(git branch --show-current)"
echo "• 最新提交: $(git log -1 --oneline)"
echo "• 远程状态: $(git status -s | wc -l | xargs echo)个未提交更改"
echo ""

# 检查工作流文件
echo "📋 工作流配置检查:"
if [ -f ".github/workflows/digital-provenance.yml" ]; then
    echo "✅ 主工作流文件存在: digital-provenance.yml"
else
    echo "❌ 主工作流文件缺失"
fi

if [ -f ".github/workflows/multi-environment-deployment.yml.disabled" ]; then
    echo "✅ 多环境工作流已禁用: multi-environment-deployment.yml.disabled"
else
    echo "⚠️ 多环境工作流状态未知"
fi
echo ""

# 检查必需的脚本文件
echo "🔧 核心脚本检查:"
REQUIRED_SCRIPTS=(
    "scripts/process_aibom.py"
    "cosign.key"
    "cosign.pub"
)

for script in "${REQUIRED_SCRIPTS[@]}"; do
    if [ -f "$script" ]; then
        echo "✅ $script 存在"
    else
        echo "❌ $script 缺失"
    fi
done
echo ""

# 检查GitHub Secrets状态提示
echo "🔑 GitHub Secrets检查提醒:"
echo "请确认以下Secrets已在GitHub仓库中设置:"
echo "• COSIGN_PRIVATE_KEY (cosign.key文件内容)"
echo "• COSIGN_PASSWORD (密钥密码)"
echo ""
echo "检查方法: https://github.com/$(git remote get-url origin | sed 's/.*github.com[:/]//' | sed 's/.git$//')/settings/secrets/actions"
echo ""

# 提供GitHub Actions链接
echo "🚀 GitHub Actions监控:"
REPO_URL=$(git remote get-url origin | sed 's/.git$//' | sed 's/https:\/\/.*@github\.com/https:\/\/github.com/')
echo "• Actions页面: $REPO_URL/actions"
echo "• 最新运行: $REPO_URL/actions/runs"
echo ""

# 预期结果说明
echo "🎯 预期运行结果:"
echo "• 工作流名称: 'AI Digital Provenance (Simplified)'"
echo "• 执行时间: 2-3分钟"
echo "• 状态: 绿色✅ (成功) 或 红色❌ (失败)"
echo "• 输出: AI检测结果和SBOM统计"
echo ""

# AI检测测试建议
echo "🧪 AI检测功能测试:"
echo "如果想测试AI检测功能，可以创建一个AI生成的测试文件:"
echo ""
echo "cat > src/app/test-ai-component.ts << 'EOF'"
echo "// Generated by Claude AI"
echo "// This is an AI-generated test component"
echo "export class TestAIComponent {"
echo "  // Auto-generated method"
echo "  testMethod() {"
echo "    console.log('AI generated test method');"
echo "  }"
echo "}"
echo "EOF"
echo ""
echo "然后提交并推送:"
echo "git add src/app/test-ai-component.ts"
echo "git commit -m 'test: 添加AI生成代码测试文件'"
echo "git push origin main"
echo ""

# 故障排除指南
echo "🆘 故障排除:"
echo "如果工作流失败，请检查:"
echo "1. GitHub Secrets是否正确设置"
echo "2. cosign.key和cosign.pub文件是否存在"
echo "3. process_aibom.py脚本是否可执行"
echo "4. 网络连接是否正常（下载Syft和Cosign）"
echo ""

echo "✅ 验证脚本执行完成"
echo "请访问GitHub Actions页面查看实际运行状态"